{
 "title": "Dashboard Monitoreo - MicroServicios_2",
 "description": "Dashboard de monitoreo para microservicios User Service y Notification Service",
 "time": { "from": "2025-11-22T04:03:24.451Z", "to": "2025-11-22T05:38:03.515Z" },
 "panels": [
  {
   "title": "Eventos por Minuto",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(events_consumed_total[1m]) * 60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Eventos Consumidos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "events_consumed_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Uso de Memoria por Servicio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"user-service|notification-service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latencia Promedio (User Service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"user-service\"} / http_request_duration_seconds_count{job=\"user-service\"}\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"user-service|notification-service\"}[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}